name: Демонстрация GitVerse CI/CD
on:
  push:
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Установка JDK
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: 'temurin'
      - name: Сборка
        run: ./gradlew build
      - name: Создание релиза
        uses: softprops/action-gh-release@v2
        with:
          files: build/libs/*.jar
          body: Автоматический релиз для коммита ${{ github.sha }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITVERSE }}
      - name: Проверка выходных файлов
        run: ls -la build/libs