# name: Демонстрация GitVerse CI/CD
on:
  push:
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Используем v3 для совместимости
      - name: Установка JDK
        uses: actions/setup-java@v3  # Используем v3 для совместимости
        with:
          java-version: "21"
          distribution: 'temurin'
      - name: Сборка
        run: ./gradlew build
      # Используем старую версию actions/upload-artifact
      - name: Сохранение JAR-файла
        uses: actions/upload-artifact@v2  # Важно: используйте v2 вместо v4
        with:
          name: plugin-release
          path: build/libs/*.jar
      - name: Проверка выходных файлов
        run: ls -la build/libs