# name: Демонстрация GitVerse CI/CD
on:
  push:
jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      RUNNER_DEBUG: 1  # Включение отладки
    steps:
      - uses: actions/checkout@v4
      - name: Установка JDK
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: 'temurin'
      - name: Сборка
        run: ./gradlew build
      - name: Сохранение JAR-файла
        uses: actions/upload-artifact@v4
        with:
          name: plugin-release
          path: build/libs/*.jar
      - name: Проверка выходных файлов
        run: ls -la build/libs