main: ru.annelo.StatisticPlugin
name: StatisticPlugin
version: "${VERSION}"
api-version: "1.21.1"
author: AUTHOR
description: DESCRIPTION
commands:
  ex:
    description: Base command for EXAMPLE
    usage: "For a list of commands, type /ex help"
