main: ru.annelo.player2statistic.StatsPlugin
name: Player2Statistic
version: "${VERSION}"
api-version: "1.21"
author: Annelo
description: Собирает и отображает статистику игроков на сервере.
commands:
  stats:
    description: Отображает статистику игрока.
    usage: "/stats [player]"
    permission: player2statistic.stats
    permission-message: "У вас нет прав для использования этой команды."
permissions:
  player2statistic.stats:
    description: Разрешение на просмотр своей статистики.
    default: true
  player2statistic.admin:
    description: Разрешение на просмотр статистики других игроков.
    default: op
