# name: Демонстрация GitHub CI/CD с автоматическим созданием тега и релиза
on:
  push:
    branches:
      - main  # Запускать workflow при пуше в ветку main

jobs:
  build-test:
    runs-on: ubuntu-latest

    env:
      RUNNER_DEBUG: 1

    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v3  # Используем v3 для GitHub

      - name: Установка JDK
        uses: actions/setup-java@v3  # Используем v3 для GitHub
        with:
          java-version: "21"
          distribution: 'temurin'

      - name: Сборка проекта
        run: ./gradlew build

      - name: Проверка выходных файлов
        run: ls -la build/libs

      - name: Создание тега через API
        env:
          API_URL: "https://api.github.com"
        run: |
          TAG_NAME="v$(date +%Y.%m.%d)-${GITHUB_RUN_NUMBER}"
          COMMIT_SHA=$(git rev-parse HEAD)
          PAYLOAD=$(jq -n --arg tag "$TAG_NAME" --arg sha "$COMMIT_SHA" \
            '{tag: $tag, object: $sha, type: "commit", message: "Auto-created tag"}')
          curl -X POST \
            -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            -H "Content-Type: application/json" \
            "$API_URL/repos/${{ github.repository }}/git/tags" \
            -d "$PAYLOAD"
          
      - name: Создание релиза и загрузка JAR-файла
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1  # Используем действие для создания релиза
        with:
          files: build/libs/*.jar  # Загружаем JAR-файл напрямую
          body: "Автоматически созданный релиз из GitHub Actions"
          token: ${{ secrets.GITHUB_TOKEN }}  # Токен для авторизации
